### PR TITLE
 Update response as discussed

### PR DESCRIPTION
**Pull request by 8176135**
Updates the response so that it matches the file names of the images correctly. No more `suit` and `value`, just a string with the file name.

### CODE REVIEW

**Comment by TamahauBrown** [comment]
Test cases:
1. Clicking equity estimate and getting response.  
image
When applying a console log here, the results of the cards being <suit>_<value> is correct, the issue is that when FE and BE merge there will lead an issue where FE will have to refactor. This is not a BE issue per se but something to take into account in case you can think of a cleaner solution. I can see a method to work with the for each in this so not the biggest issue.
**Result:** Passed

2. Testing the chances slider without the FE invoking it through an export function (So calling a Rust function)
I was unable to find this in your code and which function to call. This either a) needs to be documented please, just so I know where to call, b) still is being implemented but knowing this would be beneficial as this was an assumed test case, c) I am missing it but from the code changes I could not find anything to do with a chance slider passing a value to your function.
**Result:** Did not pass

Code notes:
image
I can figure out the overall goal of what this is doing but it was not intuitive from an initial glance, a comment header would be beneficial.

Overall: Functionality that has been added serves the correct purpose so I am happy to approve but the equity comparison needs to be implemented.

**Review by TamahauBrown — APPROVED** [review]

**Comment by 8176135** [comment]
>
    Testing the chances slider without the FE invoking it through an export function (So calling a Rust function)
    I was unable to find this in your code and which function to call. This either a) needs to be documented please, just so I know where to call, b) still is being implemented but knowing this would be beneficial as this was an assumed test case, c) I am missing it but from the code changes I could not find anything to do with a chance slider passing a value to your function.
    Result: Did not pass

I have now added the function (I think it's the function you meant?), and put some documentation on the wiki here:
https://github.com/TamahauBrown/poker-trainer/wiki/BE-to-FE-communication

it's kind of rough, so feedback definitely welcome on what could be clearer / what I missed etc.

**Comment by TamahauBrown** [comment]
image
Just for documentation purposes before I make a commit

**Comment by TamahauBrown** [comment]
Tested, LGTM

**Pull request merged**
